-   id: poetry
    name: pyright
    description: 'Static Type Checker for Python'
    entry: poetry run pyright
    language: node
    types: [python]
    require_serial: true
    always_run: true
    additional_dependencies: ["pyright@1.1.355"]

-   id: pdm
    name: pyright
    description: 'Static Type Checker for Python'
    entry: pdm run pyright
    language: node
    types: [python]
    require_serial: true
    always_run: true
    additional_dependencies: ["pyright@1.1.355"]